-- Seed data for anabolic-meal-planner
-- Idempotent: safe to re-run after adding a unique constraint on recipes.slug.
-- Nutrition values are approximate and should be verified before using in production.

insert into recipes (
  slug,
  title,
  meal_type,
  calories,
  protein_g,
  carbs_g,
  fat_g,
  ingredients,
  instructions
)
values
(
  'protein-oatmeal',
  'Protein Oatmeal',
  'breakfast',
  450,
  35,
  45,
  10,
  '["rolled oats", "whey protein", "berries", "almond milk", "cinnamon"]'::jsonb,
  'Cook oats with almond milk. Stir in whey after cooking. Top with berries and cinnamon.'
),
(
  'banana-protein-pancakes',
  'Banana Protein Pancakes',
  'breakfast',
  430,
  38,
  42,
  9,
  '["banana", "egg whites", "whey protein", "oats", "baking powder"]'::jsonb,
  'Blend ingredients into batter. Cook pancakes on a nonstick pan until golden.'
),
(
  'greek-yogurt-protein-bowl',
  'Greek Yogurt Protein Bowl',
  'breakfast',
  360,
  42,
  32,
  6,
  '["nonfat Greek yogurt", "whey protein", "blueberries", "granola", "honey"]'::jsonb,
  'Mix yogurt and whey. Top with blueberries, granola, and a small drizzle of honey.'
),
(
  'egg-white-breakfast-burrito',
  'Egg White Breakfast Burrito',
  'breakfast',
  410,
  36,
  38,
  11,
  '["egg whites", "low-carb tortilla", "turkey sausage", "spinach", "salsa", "reduced-fat cheese"]'::jsonb,
  'Cook egg whites, sausage, and spinach. Wrap with cheese and salsa in tortilla.'
),
(
  'cottage-cheese-toast',
  'Cottage Cheese Power Toast',
  'breakfast',
  390,
  34,
  36,
  10,
  '["sourdough toast", "low-fat cottage cheese", "tomato", "everything seasoning", "turkey slices"]'::jsonb,
  'Toast bread. Add cottage cheese, tomato, seasoning, and turkey slices.'
),
(
  'breakfast-turkey-hash',
  'Turkey Sweet Potato Breakfast Hash',
  'breakfast',
  520,
  42,
  48,
  16,
  '["lean ground turkey", "sweet potato", "egg whites", "bell pepper", "onion", "hot sauce"]'::jsonb,
  'Cook turkey with diced vegetables and sweet potato. Add egg whites and scramble together.'
),
(
  'protein-french-toast',
  'High-Protein French Toast',
  'breakfast',
  460,
  40,
  50,
  8,
  '["whole grain bread", "egg whites", "vanilla whey", "cinnamon", "berries", "sugar-free syrup"]'::jsonb,
  'Dip bread in egg white and whey mixture. Pan-fry and top with berries.'
),
(
  'overnight-protein-oats',
  'Overnight Protein Oats',
  'breakfast',
  420,
  35,
  52,
  8,
  '["oats", "Greek yogurt", "whey protein", "chia seeds", "berries", "almond milk"]'::jsonb,
  'Mix all ingredients in a jar and refrigerate overnight.'
),
(
  'breakfast-quesadilla',
  'Egg White Breakfast Quesadilla',
  'breakfast',
  440,
  39,
  34,
  14,
  '["egg whites", "high-fiber tortilla", "reduced-fat cheese", "black beans", "salsa", "spinach"]'::jsonb,
  'Cook egg whites and spinach. Fold into tortilla with cheese, beans, and salsa. Crisp in pan.'
),
(
  'protein-smoothie-bowl',
  'Protein Smoothie Bowl',
  'breakfast',
  390,
  37,
  44,
  7,
  '["whey protein", "frozen berries", "banana", "Greek yogurt", "almond milk", "rice cereal"]'::jsonb,
  'Blend protein, fruit, yogurt, and almond milk. Top lightly with cereal.'
),
(
  'chicken-rice-bowl',
  'Chicken Rice Bowl',
  'lunch',
  650,
  55,
  70,
  15,
  '["chicken breast", "rice", "broccoli", "soy sauce", "sriracha", "sesame seeds"]'::jsonb,
  'Cook chicken, rice, and broccoli. Combine with soy sauce and sriracha.'
),
(
  'turkey-taco-bowl',
  'Lean Turkey Taco Bowl',
  'lunch',
  590,
  52,
  55,
  16,
  '["lean ground turkey", "rice", "black beans", "lettuce", "salsa", "Greek yogurt", "taco seasoning"]'::jsonb,
  'Cook turkey with seasoning. Serve over rice and beans with lettuce, salsa, and Greek yogurt.'
),
(
  'buffalo-chicken-wrap',
  'Buffalo Chicken Wrap',
  'lunch',
  520,
  48,
  42,
  15,
  '["chicken breast", "high-fiber tortilla", "buffalo sauce", "lettuce", "Greek yogurt ranch", "reduced-fat cheese"]'::jsonb,
  'Toss chicken with buffalo sauce. Wrap with lettuce, ranch, and cheese.'
),
(
  'chicken-caesar-wrap',
  'Light Chicken Caesar Wrap',
  'lunch',
  540,
  49,
  44,
  16,
  '["chicken breast", "high-fiber tortilla", "romaine", "light Caesar dressing", "parmesan", "croutons"]'::jsonb,
  'Slice chicken and wrap with romaine, dressing, parmesan, and a few crushed croutons.'
),
(
  'tuna-rice-bowl',
  'Spicy Tuna Rice Bowl',
  'lunch',
  500,
  43,
  58,
  9,
  '["canned tuna", "rice", "cucumber", "edamame", "sriracha", "light mayo", "soy sauce"]'::jsonb,
  'Mix tuna with light mayo and sriracha. Serve over rice with cucumber and edamame.'
),
(
  'chicken-pita',
  'Chicken Tzatziki Pita',
  'lunch',
  560,
  50,
  52,
  14,
  '["chicken breast", "whole wheat pita", "tzatziki", "cucumber", "tomato", "red onion"]'::jsonb,
  'Stuff pita with grilled chicken, tzatziki, and vegetables.'
),
(
  'shrimp-burrito-bowl',
  'Shrimp Burrito Bowl',
  'lunch',
  540,
  45,
  62,
  10,
  '["shrimp", "rice", "black beans", "corn", "salsa", "lettuce", "lime"]'::jsonb,
  'Cook shrimp with spices. Serve over rice, beans, corn, lettuce, and salsa.'
),
(
  'turkey-burger-bowl',
  'Turkey Burger Bowl',
  'lunch',
  610,
  50,
  50,
  20,
  '["lean turkey patty", "potatoes", "lettuce", "pickles", "tomato", "light burger sauce"]'::jsonb,
  'Cook turkey patty and potatoes. Serve chopped over salad with pickles and sauce.'
),
(
  'chicken-pad-thai-lite',
  'Light Chicken Pad Thai',
  'lunch',
  620,
  52,
  68,
  14,
  '["chicken breast", "rice noodles", "egg whites", "bean sprouts", "carrots", "light peanut sauce"]'::jsonb,
  'Cook chicken and noodles. Toss with egg whites, vegetables, and light peanut sauce.'
),
(
  'bbq-chicken-flatbread',
  'BBQ Chicken Flatbread',
  'lunch',
  580,
  50,
  58,
  14,
  '["flatbread", "chicken breast", "BBQ sauce", "red onion", "reduced-fat mozzarella", "cilantro"]'::jsonb,
  'Top flatbread with chicken, BBQ sauce, onion, and cheese. Bake until crisp.'
),
(
  'turkey-chili',
  'Lean Turkey Chili',
  'dinner',
  560,
  50,
  48,
  15,
  '["lean ground turkey", "kidney beans", "tomatoes", "onion", "chili powder", "Greek yogurt"]'::jsonb,
  'Simmer turkey, beans, tomatoes, onion, and spices. Top with Greek yogurt.'
),
(
  'salmon-potato-asparagus',
  'Salmon Potato Asparagus Plate',
  'dinner',
  650,
  47,
  52,
  24,
  '["salmon", "potatoes", "asparagus", "lemon", "garlic", "olive oil"]'::jsonb,
  'Bake salmon, potatoes, and asparagus with lemon, garlic, and a measured amount of olive oil.'
),
(
  'chicken-fajita-plate',
  'Chicken Fajita Plate',
  'dinner',
  600,
  55,
  55,
  14,
  '["chicken breast", "peppers", "onions", "rice", "salsa", "fajita seasoning"]'::jsonb,
  'Cook chicken with peppers and onions. Serve with rice and salsa.'
),
(
  'beef-broccoli-rice',
  'Lean Beef and Broccoli Rice',
  'dinner',
  640,
  52,
  62,
  18,
  '["lean beef", "broccoli", "rice", "soy sauce", "garlic", "ginger"]'::jsonb,
  'Stir-fry lean beef and broccoli with soy, garlic, and ginger. Serve with rice.'
),
(
  'protein-mac-and-cheese',
  'High-Protein Mac and Cheese',
  'dinner',
  610,
  45,
  70,
  14,
  '["chickpea pasta", "low-fat cottage cheese", "reduced-fat cheddar", "chicken breast", "mustard powder"]'::jsonb,
  'Cook pasta. Blend cottage cheese into sauce with cheddar and spices. Add chicken.'
),
(
  'chicken-parm-bowl',
  'Chicken Parm Bowl',
  'dinner',
  620,
  56,
  58,
  15,
  '["chicken breast", "pasta", "marinara", "reduced-fat mozzarella", "parmesan", "Italian seasoning"]'::jsonb,
  'Cook chicken and pasta. Top with marinara, mozzarella, parmesan, and seasoning.'
),
(
  'pork-tenderloin-rice',
  'Pork Tenderloin Rice Plate',
  'dinner',
  630,
  52,
  60,
  16,
  '["pork tenderloin", "rice", "green beans", "teriyaki sauce", "garlic"]'::jsonb,
  'Roast pork tenderloin. Serve sliced with rice, green beans, and light teriyaki sauce.'
),
(
  'chicken-alfredo-lite',
  'Light Chicken Alfredo',
  'dinner',
  640,
  55,
  65,
  16,
  '["chicken breast", "protein pasta", "low-fat milk", "parmesan", "Greek yogurt", "garlic"]'::jsonb,
  'Cook pasta and chicken. Make light sauce with milk, parmesan, Greek yogurt, and garlic.'
),
(
  'turkey-meatball-pasta',
  'Turkey Meatball Pasta',
  'dinner',
  620,
  52,
  66,
  14,
  '["lean turkey meatballs", "protein pasta", "marinara", "zucchini", "parmesan"]'::jsonb,
  'Bake turkey meatballs. Serve with pasta, marinara, zucchini, and parmesan.'
),
(
  'shrimp-stir-fry-noodles',
  'Shrimp Stir-Fry Noodles',
  'dinner',
  590,
  46,
  70,
  10,
  '["shrimp", "rice noodles", "stir-fry vegetables", "soy sauce", "garlic", "chili paste"]'::jsonb,
  'Cook shrimp and vegetables. Toss with noodles, soy sauce, garlic, and chili paste.'
),
(
  'protein-ice-cream',
  'Protein Ice Cream',
  'snack',
  280,
  35,
  26,
  4,
  '["whey protein", "frozen banana", "almond milk", "Greek yogurt", "cocoa powder"]'::jsonb,
  'Blend ingredients until thick and creamy. Freeze briefly if needed.'
),
(
  'cottage-cheese-pudding',
  'Cottage Cheese Protein Pudding',
  'snack',
  260,
  32,
  20,
  5,
  '["low-fat cottage cheese", "chocolate whey", "cocoa powder", "sweetener", "berries"]'::jsonb,
  'Blend cottage cheese, whey, cocoa, and sweetener. Top with berries.'
),
(
  'turkey-cheese-rollups',
  'Turkey Cheese Rollups',
  'snack',
  240,
  30,
  6,
  10,
  '["turkey slices", "reduced-fat cheese", "pickles", "mustard"]'::jsonb,
  'Roll turkey around cheese and pickles. Serve with mustard.'
),
(
  'protein-mug-cake',
  'Protein Mug Cake',
  'snack',
  310,
  32,
  28,
  7,
  '["whey protein", "egg whites", "banana", "cocoa powder", "baking powder"]'::jsonb,
  'Mix in a mug and microwave until set.'
),
(
  'edamame-chicken-snack-box',
  'Edamame Chicken Snack Box',
  'snack',
  330,
  36,
  24,
  8,
  '["edamame", "chicken breast", "grapes", "light string cheese"]'::jsonb,
  'Pack cooked chicken, edamame, grapes, and string cheese together.'
),
(
  'greek-yogurt-cheesecake-bowl',
  'Greek Yogurt Cheesecake Bowl',
  'snack',
  300,
  35,
  28,
  4,
  '["Greek yogurt", "vanilla protein powder", "cream cheese powder", "strawberries", "graham cracker crumbs"]'::jsonb,
  'Mix yogurt with protein and flavoring. Top with strawberries and crumbs.'
),
(
  'protein-hot-chocolate',
  'Protein Hot Chocolate',
  'snack',
  220,
  28,
  18,
  4,
  '["chocolate protein powder", "skim milk", "cocoa powder", "sweetener"]'::jsonb,
  'Warm milk. Whisk in protein, cocoa, and sweetener off heat.'
),
(
  'apple-protein-dip',
  'Apple with Protein Cheesecake Dip',
  'snack',
  280,
  25,
  38,
  3,
  '["apple", "Greek yogurt", "vanilla whey", "cinnamon", "sweetener"]'::jsonb,
  'Mix yogurt, whey, cinnamon, and sweetener. Serve with apple slices.'
),
(
  'rice-cake-tuna-stack',
  'Tuna Rice Cake Stack',
  'snack',
  260,
  30,
  24,
  4,
  '["rice cakes", "canned tuna", "light mayo", "sriracha", "cucumber"]'::jsonb,
  'Mix tuna with light mayo and sriracha. Spoon onto rice cakes with cucumber.'
),
(
  'protein-cereal-bowl',
  'Protein Cereal Bowl',
  'snack',
  330,
  32,
  42,
  4,
  '["high-protein cereal", "skim milk", "whey protein", "berries"]'::jsonb,
  'Mix whey into milk. Pour over cereal and berries.'
),
(
  'chicken-shawarma-bowl',
  'Chicken Shawarma Bowl',
  'lunch',
  610,
  54,
  58,
  15,
  '["chicken breast", "rice", "cucumber", "tomato", "Greek yogurt sauce", "shawarma seasoning"]'::jsonb,
  'Season and cook chicken. Serve over rice with vegetables and yogurt sauce.'
),
(
  'korean-beef-bowl-lite',
  'Light Korean Beef Bowl',
  'dinner',
  620,
  50,
  64,
  16,
  '["lean ground beef", "rice", "carrots", "cucumber", "soy sauce", "gochujang"]'::jsonb,
  'Cook beef with soy and gochujang. Serve over rice with vegetables.'
),
(
  'teriyaki-chicken-pineapple-bowl',
  'Teriyaki Chicken Pineapple Bowl',
  'lunch',
  600,
  52,
  65,
  12,
  '["chicken breast", "rice", "pineapple", "broccoli", "light teriyaki sauce"]'::jsonb,
  'Cook chicken and broccoli. Serve with rice, pineapple, and light teriyaki sauce.'
),
(
  'chicken-gyro-bowl',
  'Chicken Gyro Bowl',
  'dinner',
  590,
  53,
  55,
  14,
  '["chicken breast", "potatoes", "tzatziki", "cucumber", "tomato", "oregano"]'::jsonb,
  'Cook chicken and potatoes. Serve with tzatziki and vegetables.'
),
(
  'buffalo-turkey-meatballs',
  'Buffalo Turkey Meatballs',
  'dinner',
  560,
  52,
  42,
  17,
  '["lean ground turkey", "breadcrumbs", "egg whites", "buffalo sauce", "potatoes", "celery"]'::jsonb,
  'Bake turkey meatballs. Toss with buffalo sauce and serve with potatoes and celery.'
),
(
  'chipotle-chicken-bowl',
  'Chipotle Chicken Bowl',
  'lunch',
  630,
  56,
  64,
  14,
  '["chicken breast", "rice", "black beans", "corn", "salsa", "chipotle peppers", "Greek yogurt"]'::jsonb,
  'Cook chipotle chicken. Serve over rice and beans with corn, salsa, and yogurt.'
),
(
  'salsa-verde-chicken-tacos',
  'Salsa Verde Chicken Tacos',
  'dinner',
  540,
  48,
  52,
  12,
  '["chicken breast", "corn tortillas", "salsa verde", "cabbage", "Greek yogurt", "lime"]'::jsonb,
  'Shred chicken with salsa verde. Serve in tortillas with cabbage, yogurt, and lime.'
),
(
  'thai-basil-turkey-rice',
  'Thai Basil Turkey Rice',
  'dinner',
  610,
  52,
  60,
  15,
  '["lean ground turkey", "rice", "basil", "green beans", "soy sauce", "chili garlic sauce"]'::jsonb,
  'Cook turkey with beans, basil, soy sauce, and chili garlic sauce. Serve over rice.'
),
(
  'chicken-souvlaki-plate',
  'Chicken Souvlaki Plate',
  'dinner',
  620,
  55,
  58,
  16,
  '["chicken breast", "pita", "Greek salad", "tzatziki", "lemon", "oregano"]'::jsonb,
  'Grill lemon oregano chicken. Serve with pita, salad, and tzatziki.'
),
(
  'protein-breakfast-sandwich',
  'Protein Breakfast Sandwich',
  'breakfast',
  430,
  38,
  35,
  14,
  '["English muffin", "egg whites", "turkey bacon", "reduced-fat cheese", "spinach"]'::jsonb,
  'Cook egg whites and turkey bacon. Assemble on muffin with cheese and spinach.'
),
(
  'turkey-sausage-egg-bowl',
  'Turkey Sausage Egg Bowl',
  'breakfast',
  480,
  42,
  32,
  18,
  '["turkey sausage", "egg whites", "potatoes", "spinach", "salsa"]'::jsonb,
  'Cook potatoes and turkey sausage. Add spinach and egg whites. Top with salsa.'
),
(
  'mocha-protein-shake',
  'Mocha Protein Shake',
  'snack',
  250,
  34,
  20,
  4,
  '["coffee", "chocolate whey", "banana", "almond milk", "ice"]'::jsonb,
  'Blend all ingredients until smooth.'
),
(
  'peanut-butter-protein-yogurt',
  'Peanut Butter Protein Yogurt',
  'snack',
  340,
  38,
  24,
  10,
  '["Greek yogurt", "peanut butter powder", "vanilla whey", "banana slices"]'::jsonb,
  'Mix yogurt, peanut butter powder, and whey. Top with banana.'
),
(
  'chicken-noodle-soup-protein',
  'High-Protein Chicken Noodle Soup',
  'lunch',
  520,
  48,
  55,
  9,
  '["chicken breast", "egg noodles", "carrots", "celery", "chicken broth", "parsley"]'::jsonb,
  'Simmer broth with vegetables, noodles, and chicken until tender.'
),
(
  'turkey-sloppy-joe-bowl',
  'Turkey Sloppy Joe Bowl',
  'dinner',
  610,
  50,
  62,
  14,
  '["lean ground turkey", "potatoes", "tomato sauce", "onion", "pickles", "mustard"]'::jsonb,
  'Cook turkey with sauce and onion. Serve over potatoes with pickles and mustard.'
),
(
  'bbq-pulled-chicken-potato',
  'BBQ Pulled Chicken Potato',
  'dinner',
  590,
  52,
  60,
  12,
  '["chicken breast", "baked potato", "BBQ sauce", "Greek yogurt", "green onion"]'::jsonb,
  'Shred cooked chicken with BBQ sauce. Serve over baked potato with yogurt and green onion.'
),
(
  'spicy-chicken-ramen-lite',
  'Spicy Chicken Ramen Lite',
  'dinner',
  620,
  50,
  68,
  14,
  '["chicken breast", "ramen noodles", "egg whites", "bok choy", "mushrooms", "chili paste"]'::jsonb,
  'Cook noodles with vegetables and chicken. Stir in egg whites for extra protein.'
),
(
  'chicken-enchilada-bake',
  'Chicken Enchilada Bake',
  'dinner',
  600,
  54,
  56,
  15,
  '["chicken breast", "corn tortillas", "enchilada sauce", "black beans", "reduced-fat cheese"]'::jsonb,
  'Layer tortillas, chicken, beans, sauce, and cheese. Bake until bubbly.'
),
(
  'lemon-garlic-shrimp-rice',
  'Lemon Garlic Shrimp Rice',
  'dinner',
  540,
  44,
  58,
  10,
  '["shrimp", "rice", "zucchini", "lemon", "garlic", "parmesan"]'::jsonb,
  'Cook shrimp with lemon and garlic. Serve with rice, zucchini, and parmesan.'
),
(
  'high-protein-chicken-salad',
  'High-Protein Chicken Salad',
  'lunch',
  500,
  50,
  28,
  18,
  '["chicken breast", "Greek yogurt", "celery", "grapes", "whole wheat bread", "lettuce"]'::jsonb,
  'Mix chicken with Greek yogurt, celery, and grapes. Serve with bread and lettuce.'
),
(
  'steak-potato-salad',
  'Lean Steak Potato Salad',
  'dinner',
  640,
  50,
  50,
  22,
  '["sirloin steak", "potatoes", "arugula", "tomatoes", "light vinaigrette"]'::jsonb,
  'Cook steak and potatoes. Serve over arugula with tomatoes and vinaigrette.'
),
(
  'chicken-curry-rice-lite',
  'Light Chicken Curry Rice',
  'dinner',
  630,
  52,
  65,
  14,
  '["chicken breast", "rice", "light coconut milk", "curry powder", "peas", "carrots"]'::jsonb,
  'Simmer chicken and vegetables in light curry sauce. Serve with rice.'
),
(
  'turkey-lasagna-bowl',
  'Turkey Lasagna Bowl',
  'dinner',
  620,
  55,
  58,
  16,
  '["lean ground turkey", "pasta", "marinara", "low-fat ricotta", "mozzarella", "spinach"]'::jsonb,
  'Cook turkey and pasta. Mix with marinara, ricotta, mozzarella, and spinach.'
),
(
  'egg-white-omelet-plate',
  'Egg White Omelet Plate',
  'breakfast',
  380,
  40,
  28,
  9,
  '["egg whites", "reduced-fat cheese", "spinach", "mushrooms", "toast", "salsa"]'::jsonb,
  'Cook omelet with vegetables and cheese. Serve with toast and salsa.'
),
(
  'blueberry-protein-muffin-bowl',
  'Blueberry Protein Muffin Bowl',
  'breakfast',
  410,
  35,
  48,
  7,
  '["oats", "whey protein", "blueberries", "Greek yogurt", "baking powder"]'::jsonb,
  'Bake mixed ingredients in a ramekin until set, or microwave as a bowl.'
),
(
  'cinnamon-roll-protein-oats',
  'Cinnamon Roll Protein Oats',
  'breakfast',
  430,
  36,
  50,
  8,
  '["oats", "vanilla whey", "Greek yogurt", "cinnamon", "cream cheese powder"]'::jsonb,
  'Cook oats. Stir in whey and top with yogurt mixed with cinnamon and cream cheese powder.'
),
(
  'protein-breakfast-tacos',
  'Protein Breakfast Tacos',
  'breakfast',
  450,
  40,
  38,
  13,
  '["corn tortillas", "egg whites", "turkey sausage", "salsa", "reduced-fat cheese"]'::jsonb,
  'Cook sausage and egg whites. Serve in tortillas with salsa and cheese.'
),
(
  'chicken-pesto-pasta-lite',
  'Light Chicken Pesto Pasta',
  'dinner',
  650,
  55,
  66,
  17,
  '["chicken breast", "protein pasta", "light pesto", "cherry tomatoes", "spinach"]'::jsonb,
  'Cook pasta and chicken. Toss with light pesto, tomatoes, and spinach.'
),
(
  'mediterranean-tuna-pita',
  'Mediterranean Tuna Pita',
  'lunch',
  520,
  42,
  48,
  14,
  '["canned tuna", "whole wheat pita", "Greek yogurt", "cucumber", "tomato", "feta"]'::jsonb,
  'Mix tuna with yogurt. Stuff into pita with vegetables and feta.'
),
(
  'sweet-chili-chicken-bowl',
  'Sweet Chili Chicken Bowl',
  'lunch',
  610,
  52,
  68,
  10,
  '["chicken breast", "rice", "broccoli", "sweet chili sauce", "lime"]'::jsonb,
  'Cook chicken and broccoli. Serve over rice with sweet chili sauce and lime.'
),
(
  'protein-chia-pudding',
  'Protein Chia Pudding',
  'snack',
  320,
  30,
  28,
  9,
  '["chia seeds", "vanilla whey", "almond milk", "Greek yogurt", "berries"]'::jsonb,
  'Mix ingredients and refrigerate until thick. Top with berries.'
),
(
  'cottage-cheese-salsa-bowl',
  'Cottage Cheese Salsa Bowl',
  'snack',
  260,
  32,
  18,
  6,
  '["low-fat cottage cheese", "salsa", "black beans", "tortilla chips", "cilantro"]'::jsonb,
  'Top cottage cheese with salsa, beans, crushed chips, and cilantro.'
),
(
  'chocolate-banana-protein-wrap',
  'Chocolate Banana Protein Wrap',
  'snack',
  350,
  30,
  45,
  7,
  '["high-fiber tortilla", "chocolate whey", "Greek yogurt", "banana", "peanut butter powder"]'::jsonb,
  'Mix whey, yogurt, and peanut butter powder. Spread in tortilla with banana and roll.'
),
(
  'chicken-pizza-bagel',
  'Chicken Pizza Bagel',
  'snack',
  380,
  34,
  38,
  9,
  '["bagel thin", "chicken breast", "marinara", "reduced-fat mozzarella", "Italian seasoning"]'::jsonb,
  'Top bagel with chicken, marinara, and cheese. Bake until melted.'
),
(
  'high-protein-queso-dip',
  'High-Protein Queso Dip',
  'snack',
  300,
  28,
  20,
  10,
  '["low-fat cottage cheese", "reduced-fat cheddar", "salsa", "tortilla chips"]'::jsonb,
  'Blend cottage cheese, warm with cheddar and salsa, and serve with chips.'
)
on conflict (slug) do update
set
  title = excluded.title,
  meal_type = excluded.meal_type,
  calories = excluded.calories,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions;
